apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: getbestanswers-hpa
  namespace: getbestanswers-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: getbestanswers-deployment
  minReplicas: 1
  maxReplicas: 200
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50